#!/bin/sh
#
# ufetch-mxlinux - tiny system info for MX lInux

## INFO

# user is already defined
host="$(hostname)"
os='MX Linux'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${red}"		# labels
nc="${reset}${bold}${red}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${bold}${red}"		# first color
c1="${reset}${red}"				# second color

## OUTPUT

cat <<EOF

${lc}############################${lc}   ${USER}${ic}@${lc}${host}${reset}
${lc}############################${lc}   OS	:  ${ic}${os}${reset} 
${lc}############################${lc}   KERNEL  	:  ${ic}${kernel}${reset}
${lc}############################${lc}   UPTIME  	:  ${ic}${uptime}${reset}
${ic}############################${lc}   PACKAGES	:  ${ic}${packages}${reset}
${ic}############################${lc}   SHELL   	:  ${ic}${shell}${reset}
${ic}############################${lc}   ${envtype}	:  ${ic}${WM}${reset} 
${ic}############################	
EOF
